<form>
    <input type="text" name="text" value="<?=$text;?>" />
    <input type="submit" value="submit" />
</form>

<?php if (isset($searchResults)): ?>
    <?php if (isset($searchResults['stat']) && $searchResults['stat'] == 'ok'): ?>
        <?php foreach ($searchResults['photos']['photo'] as $photo): ?>
            <a target="_blank" href="http://www.flickr.com/photos/<?=$photo['owner']?>/<?=$photo['id']?>/"><img src="http://farm<?=$photo['farm']?>.staticflickr.com/<?=$photo['server']?>/<?=$photo['id']?>_<?=$photo['secret']?>_t.jpg" /></a>
        <?php endforeach; ?>

        <br />

        Page <?=$searchResults['photos']['page']?> of <?=$searchResults['photos']['pages']?>

        <br />

        <?php if ($searchResults['photos']['pages'] > 0): ?>
            <?php if ($searchResults['photos']['page'] > ($pagerCycle + 1)): ?>
                <a href="/search?text=<?=$text?>&page=1">1</a> &hellip;
            <?php endif; ?>

            <?php if ($searchResults['photos']['page'] > 1): ?>
                <a href="/search?text=<?=$text?>&page=<?=($searchResults['photos']['page'] - 1)?>"><</a>
            <?php endif; ?>

            <?php for ($i = ($searchResults['photos']['page'] - $pagerCycle); $i <= ($searchResults['photos']['page'] + $pagerCycle); $i++): ?>
                <?php if ($i >= 1 && $i <= $searchResults['photos']['pages']): ?>
                    <?php if($searchResults['photos']['page'] == $i):?>
                        <?=$i?>
                    <? else: ?>
                        <a href="/search?text=<?=$text?>&page=<?=$i?>"><?=$i?></a>
                    <? endif; ?>
                <?php endif; ?>
            <?php endfor; ?>

            <?php if ($searchResults['photos']['page'] < $searchResults['photos']['pages']): ?>
                <a href="/search?text=<?=$text?>&page=<?=($searchResults['photos']['page'] + 1)?>">></a>
            <?php endif; ?>

            <?php if ($searchResults['photos']['page'] < ($searchResults['photos']['pages'] - $pagerCycle - 1)): ?>
                &hellip; <a href="/search?text=<?=$text?>&page=<?=$searchResults['photos']['pages']?>"><?=$searchResults['photos']['pages']?></a>
            <?php endif; ?>

        <?php endif; ?>

        <br />

        Total found: <?=$searchResults['photos']['total']?>
    <?php endif;?>
<?php endif; ?>